### ISSUE TITLE
Move `tslint` to devDependencies list

### ISSUE THREAD

**Issue by lukeed** [NeekSandhu/onigasm#20]
Hey there,

I'm not very familiar with this module (sorry!) but I discovered that it's pulling in `tslint` as a dependency, which makes it significantly harder/impossible to use in modern browsers with ESM.

And in Node.js projects, it forces `tslint` ([and all that comes with it](https://npm.anvaka.com/#/view/2d/onigasm)) to be installed ... even though it [appears to do nothing](https://github.com/NeekSandhu/onigasm/search?q=tslint&unscoped_q=tslint).

Thanks!

**Comment by NeekSandhu** [comment]
Please see if this fixes the bundling issue - https://github.com/octref/shiki/issues/22#issuecomment-643601686

Will push the patch, over the weekend sometime. cheers.

**Comment by lukeed** [comment]
I know it can be bypassed. It just shouldn't be there.

**Comment by octref** [comment]
Hey @NeekSandhu, do you mind merging #22 and make this happen?

I'm in the process of reducing shiki's size, and `tslint` dependency is 3MB.

**Comment by NeekSandhu** [comment]
@octref @lukeed apologies for the slack guys. will get this sorted tonight 👍

**Comment by zikaari** [comment]
`2.2.5` is now live, can you please double-check if everything's nominal?

**Comment by octref** [comment]
Yes everything's normal, thanks!
